## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("Weather_Database/WeatherPy_Database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Kadhan,PK,24.4810,68.9859,78.82,63,5,14.00,clear sky
1,1,Cape Town,ZA,-33.9258,18.4232,70.00,72,0,6.91,clear sky
2,2,Castro,BR,-24.7911,-50.0119,71.64,84,100,6.31,overcast clouds
3,3,Vallenar,CL,-28.5708,-70.7581,80.51,30,0,8.70,clear sky
4,4,Sao Joao Da Barra,BR,-21.6403,-41.0511,86.00,66,20,6.91,few clouds

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 60
What is the maximum temperature you would like for your trip? 85

In [4]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & 
                                      (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Kadhan,PK,24.4810,68.9859,78.82,63,5,14.00,clear sky
1,1,Cape Town,ZA,-33.9258,18.4232,70.00,72,0,6.91,clear sky
2,2,Castro,BR,-24.7911,-50.0119,71.64,84,100,6.31,overcast clouds
3,3,Vallenar,CL,-28.5708,-70.7581,80.51,30,0,8.70,clear sky
5,5,Copiapo,CL,-27.3667,-70.3333,68.00,52,0,10.36,clear sky
6,6,Tahta,EG,26.7693,31.5021,66.20,27,0,17.27,clear sky
7,7,Meulaboh,ID,4.1363,96.1285,77.27,86,96,2.37,overcast clouds
9,9,Vila Velha,BR,-20.3297,-40.2925,82.40,65,40,6.91,scattered clouds
10,10,Bredasdorp,ZA,-34.5322,20.0403,62.60,82,100,13.80,overcast clouds
12,12,Coquimbo,CL,-29.9533,-71.3436,64.40,63,40,9.22,scattered clouds

In [5]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City_ID                378
City                   378
Country                373
Lat                    378
Lng                    378
Max Temp               378
Humidity               378
Cloudiness             378
Wind Speed             378
Current Description    378
dtype: int64

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.

In [7]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Kadhan,PK,78.82,clear sky,24.4810,68.9859,
1,Cape Town,ZA,70.00,clear sky,-33.9258,18.4232,
2,Castro,BR,71.64,overcast clouds,-24.7911,-50.0119,
3,Vallenar,CL,80.51,clear sky,-28.5708,-70.7581,
5,Copiapo,CL,68.00,clear sky,-27.3667,-70.3333,
6,Tahta,EG,66.20,clear sky,26.7693,31.5021,
7,Meulaboh,ID,77.27,overcast clouds,4.1363,96.1285,
9,Vila Velha,BR,82.40,scattered clouds,-20.3297,-40.2925,
10,Bredasdorp,ZA,62.60,overcast clouds,-34.5322,20.0403,
12,Coquimbo,CL,64.40,scattered clouds,-29.9533,-71.3436,

In [8]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key,
    "location": "Lat, Lng"
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    
    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try: 
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found...skipping")

Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping

In [20]:
hotel_df.head(20)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Kadhan,PK,78.82,clear sky,24.4810,68.9859,ڳوٺ چوڌري جلال الدين جٽ
1,Cape Town,ZA,70.00,clear sky,-33.9258,18.4232,Southern Sun Waterfront Cape Town
2,Castro,BR,71.64,overcast clouds,-24.7911,-50.0119,CHACARA BAILLY
3,Vallenar,CL,80.51,clear sky,-28.5708,-70.7581,Humacao Bed & Breakfast
5,Copiapo,CL,68.00,clear sky,-27.3667,-70.3333,San Francisco de La Selva
6,Tahta,EG,66.20,clear sky,26.7693,31.5021,El Salam Hotel
7,Meulaboh,ID,77.27,overcast clouds,4.1363,96.1285,Kost Pria
9,Vila Velha,BR,82.40,scattered clouds,-20.3297,-40.2925,Quality Suites Vila Velha
10,Bredasdorp,ZA,62.60,overcast clouds,-34.5322,20.0403,Bredasdorp Country Manor
12,Coquimbo,CL,64.40,scattered clouds,-29.9533,-71.3436,Punto de encuentro
15,Souillac,MU,77.00,few clouds,-20.5167,57.5167,Shanti Maurice Resort & Spa
16,Saldanha,ZA,68.00,overcast clouds,-33.0117,17.9442,Blue Bay Lodge
17,Necochea,AR,69.01,scattered clouds,-38.5473,-58.7368,dyd -mar Hotel
20,Ati,TD,81.50,scattered clouds,13.2154,18.3353,
22,Pontes E Lacerda,BR,82.94,broken clouds,-15.2261,-59.3353,Hotel Bressan
24,Asfi,MA,62.58,scattered clouds,32.2994,-9.2372,Hôtel Abda
25,Dingle,PH,76.23,overcast clouds,10.9995,122.6711,SEGAYA PROPERTY
26,Kalabo,ZM,70.95,overcast clouds,-14.9700,22.6814,Sikakubete Guest House Kalabo Town Council
27,Kudahuvadhoo,MV,80.26,overcast clouds,2.6708,72.8944,Niyama Private Islands Maldives
28,Conceicao Do Araguaia,BR,81.57,broken clouds,-8.2578,-49.2647,Tarumã Tropical Hotel

In [19]:
# 7. Drop the rows where there is no Hotel Name.
clean_hotel_df = hotel_df[hotel_df["Hotel Name"] != ""]
clean_hotel_df.head(15)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Kadhan,PK,78.82,clear sky,24.4810,68.9859,ڳوٺ چوڌري جلال الدين جٽ
1,Cape Town,ZA,70.00,clear sky,-33.9258,18.4232,Southern Sun Waterfront Cape Town
2,Castro,BR,71.64,overcast clouds,-24.7911,-50.0119,CHACARA BAILLY
3,Vallenar,CL,80.51,clear sky,-28.5708,-70.7581,Humacao Bed & Breakfast
5,Copiapo,CL,68.00,clear sky,-27.3667,-70.3333,San Francisco de La Selva
6,Tahta,EG,66.20,clear sky,26.7693,31.5021,El Salam Hotel
7,Meulaboh,ID,77.27,overcast clouds,4.1363,96.1285,Kost Pria
9,Vila Velha,BR,82.40,scattered clouds,-20.3297,-40.2925,Quality Suites Vila Velha
10,Bredasdorp,ZA,62.60,overcast clouds,-34.5322,20.0403,Bredasdorp Country Manor
12,Coquimbo,CL,64.40,scattered clouds,-29.9533,-71.3436,Punto de encuentro
15,Souillac,MU,77.00,few clouds,-20.5167,57.5167,Shanti Maurice Resort & Spa
16,Saldanha,ZA,68.00,overcast clouds,-33.0117,17.9442,Blue Bay Lodge
17,Necochea,AR,69.01,scattered clouds,-38.5473,-58.7368,dyd -mar Hotel
22,Pontes E Lacerda,BR,82.94,broken clouds,-15.2261,-59.3353,Hotel Bressan
24,Asfi,MA,62.58,scattered clouds,32.2994,-9.2372,Hôtel Abda

In [16]:
# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_vacation.csv"

# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [20]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [21]:
# 11a. Add a marker layer for each city to the map. 
locations = clean_hotel_df[["Lat", "Lng"]]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))